version: '3.8'
services: 
  #FRONTEND
  front:
    build:
      context: ./frontend
    ports: 
        - 3000:80
    depends_on: 
        - backend

  # BACKEND
  backend:
    build:
      context: ./lib_catalog
    command: /bin/sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports: 
        - 8000:8000
    depends_on:
        - database

  # DATABASE
  database:
    build:
      context: ./db_postgres
    image: postgres:12-alpine
    ports: 
        - 5432:5432
    environment: 
        - POSTGRES_DB=${DB_NAME}
        - POSTGRES_USER=${DB_USER}
        - POSTGRES_PASSWORD=${DB_PASSWORD}
        - POSTGRES_HOST_AUTH_METHOD=trust

